# Generated by Django 4.2.7 on 2024-05-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="recommended",
            field=models.BooleanField(default=False),
        ),
    ]
